url: "https://phpdd.org"
baseurl: ""
title: "PHP Developer Day 2024 by PHP USERGROUP DRESDEN e.V."
description: >
  The community conference for PHP developers and beyond 

logo: "/assets/images/PHPDD24-Logo.svg"
cover: "/assets/images/PHPUGDD-Imagebild.webp"
paginate: 5
